import type { Metadata } from "next";
import { Inter } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import Header from "@/components/Header";
import BlackoutSchedule from "@/components/BlackoutSchedule";
import localFont from "next/font/local";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yasno app",
  description: "Generated by create next app",
};

const yasnoRaleway = localFont({
  src: [
    {
      path: "./fonts/YasnoRaleway-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/YasnoRaleway-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, yasnoRaleway.className)}>
        <BlackoutSchedule />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
